package Andes2.model.vo;

import java.math.BigDecimal;

import oracle.jbo.domain.RowID;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 01 20:17:37 CLT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class coAsignacionEditImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        EmplRut {
            public Object get(coAsignacionEditImpl obj) {
                return obj.getEmplRut();
            }

            public void put(coAsignacionEditImpl obj, Object value) {
                obj.setEmplRut((String)value);
            }
        }
        ,
        GrpoNombre {
            public Object get(coAsignacionEditImpl obj) {
                return obj.getGrpoNombre();
            }

            public void put(coAsignacionEditImpl obj, Object value) {
                obj.setGrpoNombre((String)value);
            }
        }
        ,
        CoagFecha {
            public Object get(coAsignacionEditImpl obj) {
                return obj.getCoagFecha();
            }

            public void put(coAsignacionEditImpl obj, Object value) {
                obj.setCoagFecha((Timestamp)value);
            }
        }
        ,
        CoagVersion {
            public Object get(coAsignacionEditImpl obj) {
                return obj.getCoagVersion();
            }

            public void put(coAsignacionEditImpl obj, Object value) {
                obj.setCoagVersion((BigDecimal)value);
            }
        }
        ,
        RowID {
            public Object get(coAsignacionEditImpl obj) {
                return obj.getRowID();
            }

            public void put(coAsignacionEditImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EmpleadosEdit {
            public Object get(coAsignacionEditImpl obj) {
                return obj.getEmpleadosEdit();
            }

            public void put(coAsignacionEditImpl obj, Object value) {
                obj.setEmpleadosEdit((EntityImpl)value);
            }
        }
        ,
        GruposEO {
            public Object get(coAsignacionEditImpl obj) {
                return obj.getGruposEO();
            }

            public void put(coAsignacionEditImpl obj, Object value) {
                obj.setGruposEO((EntityImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(coAsignacionEditImpl object);

        public abstract void put(coAsignacionEditImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int EMPLRUT = AttributesEnum.EmplRut.index();
    public static final int GRPONOMBRE = AttributesEnum.GrpoNombre.index();
    public static final int COAGFECHA = AttributesEnum.CoagFecha.index();
    public static final int COAGVERSION = AttributesEnum.CoagVersion.index();
    public static final int ROWID = AttributesEnum.RowID.index();
    public static final int EMPLEADOSEDIT = AttributesEnum.EmpleadosEdit.index();
    public static final int GRUPOSEO = AttributesEnum.GruposEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public coAsignacionEditImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("Andes2.model.vo.coAsignacionEdit");
    }

    /**
     * Gets the attribute value for EmplRut, using the alias name EmplRut.
     * @return the value of EmplRut
     */
    public String getEmplRut() {
        return (String)getAttributeInternal(EMPLRUT);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmplRut.
     * @param value value to set the EmplRut
     */
    public void setEmplRut(String value) {
        setAttributeInternal(EMPLRUT, value);
    }

    /**
     * Gets the attribute value for GrpoNombre, using the alias name GrpoNombre.
     * @return the value of GrpoNombre
     */
    public String getGrpoNombre() {
        return (String)getAttributeInternal(GRPONOMBRE);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrpoNombre.
     * @param value value to set the GrpoNombre
     */
    public void setGrpoNombre(String value) {
        setAttributeInternal(GRPONOMBRE, value);
    }

    /**
     * Gets the attribute value for CoagFecha, using the alias name CoagFecha.
     * @return the value of CoagFecha
     */
    public Timestamp getCoagFecha() {
        return (Timestamp)getAttributeInternal(COAGFECHA);
    }

    /**
     * Sets <code>value</code> as the attribute value for CoagFecha.
     * @param value value to set the CoagFecha
     */
    public void setCoagFecha(Timestamp value) {
        setAttributeInternal(COAGFECHA, value);
    }

    /**
     * Gets the attribute value for CoagVersion, using the alias name CoagVersion.
     * @return the value of CoagVersion
     */
    public BigDecimal getCoagVersion() {
        return (BigDecimal)getAttributeInternal(COAGVERSION);
    }

    /**
     * Sets <code>value</code> as the attribute value for CoagVersion.
     * @param value value to set the CoagVersion
     */
    public void setCoagVersion(BigDecimal value) {
        setAttributeInternal(COAGVERSION, value);
    }

    /**
     * Gets the attribute value for RowID, using the alias name RowID.
     * @return the value of RowID
     */
    public RowID getRowID() {
        return (RowID)getAttributeInternal(ROWID);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getEmpleadosEdit() {
        return (EntityImpl)getAttributeInternal(EMPLEADOSEDIT);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setEmpleadosEdit(EntityImpl value) {
        setAttributeInternal(EMPLEADOSEDIT, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getGruposEO() {
        return (EntityImpl)getAttributeInternal(GRUPOSEO);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setGruposEO(EntityImpl value) {
        setAttributeInternal(GRUPOSEO, value);
    }

}
