package Andes2.model.vo;

import oracle.jbo.Key;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 01 19:25:33 CLT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GruposImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        GrpoNombre {
            public Object get(GruposImpl obj) {
                return obj.getGrpoNombre();
            }

            public void put(GruposImpl obj, Object value) {
                obj.setGrpoNombre((String)value);
            }
        }
        ,
        GrpoLider {
            public Object get(GruposImpl obj) {
                return obj.getGrpoLider();
            }

            public void put(GruposImpl obj, Object value) {
                obj.setGrpoLider((String)value);
            }
        }
        ,
        GrpoFechaInicio {
            public Object get(GruposImpl obj) {
                return obj.getGrpoFechaInicio();
            }

            public void put(GruposImpl obj, Object value) {
                obj.setGrpoFechaInicio((Timestamp)value);
            }
        }
        ,
        GrpoFechaTermino {
            public Object get(GruposImpl obj) {
                return obj.getGrpoFechaTermino();
            }

            public void put(GruposImpl obj, Object value) {
                obj.setGrpoFechaTermino((Timestamp)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(GruposImpl object);

        public abstract void put(GruposImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int GRPONOMBRE = AttributesEnum.GrpoNombre.index();
    public static final int GRPOLIDER = AttributesEnum.GrpoLider.index();
    public static final int GRPOFECHAINICIO = AttributesEnum.GrpoFechaInicio.index();
    public static final int GRPOFECHATERMINO = AttributesEnum.GrpoFechaTermino.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GruposImpl() {
    }

    /**
     * Gets the attribute value for GrpoNombre, using the alias name GrpoNombre.
     * @return the value of GrpoNombre
     */
    public String getGrpoNombre() {
        return (String)getAttributeInternal(GRPONOMBRE);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrpoNombre.
     * @param value value to set the GrpoNombre
     */
    public void setGrpoNombre(String value) {
        setAttributeInternal(GRPONOMBRE, value);
    }

    /**
     * Gets the attribute value for GrpoLider, using the alias name GrpoLider.
     * @return the value of GrpoLider
     */
    public String getGrpoLider() {
        return (String)getAttributeInternal(GRPOLIDER);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrpoLider.
     * @param value value to set the GrpoLider
     */
    public void setGrpoLider(String value) {
        setAttributeInternal(GRPOLIDER, value);
    }

    /**
     * Gets the attribute value for GrpoFechaInicio, using the alias name GrpoFechaInicio.
     * @return the value of GrpoFechaInicio
     */
    public Timestamp getGrpoFechaInicio() {
        return (Timestamp)getAttributeInternal(GRPOFECHAINICIO);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrpoFechaInicio.
     * @param value value to set the GrpoFechaInicio
     */
    public void setGrpoFechaInicio(Timestamp value) {
        setAttributeInternal(GRPOFECHAINICIO, value);
    }

    /**
     * Gets the attribute value for GrpoFechaTermino, using the alias name GrpoFechaTermino.
     * @return the value of GrpoFechaTermino
     */
    public Timestamp getGrpoFechaTermino() {
        return (Timestamp)getAttributeInternal(GRPOFECHATERMINO);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrpoFechaTermino.
     * @param value value to set the GrpoFechaTermino
     */
    public void setGrpoFechaTermino(Timestamp value) {
        setAttributeInternal(GRPOFECHATERMINO, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @param grpoNombre key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String grpoNombre) {
        return new Key(new Object[]{grpoNombre});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("Andes2.model.vo.Grupos");
    }
}
