package Andes2.model.vo;

import oracle.jbo.Key;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 01 19:53:06 CLT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ListaSkillEditImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        SkllId {
            public Object get(ListaSkillEditImpl obj) {
                return obj.getSkllId();
            }

            public void put(ListaSkillEditImpl obj, Object value) {
                obj.setSkllId((String)value);
            }
        }
        ,
        CrgoId {
            public Object get(ListaSkillEditImpl obj) {
                return obj.getCrgoId();
            }

            public void put(ListaSkillEditImpl obj, Object value) {
                obj.setCrgoId((String)value);
            }
        }
        ,
        SkllNombre {
            public Object get(ListaSkillEditImpl obj) {
                return obj.getSkllNombre();
            }

            public void put(ListaSkillEditImpl obj, Object value) {
                obj.setSkllNombre((String)value);
            }
        }
        ,
        Cargos {
            public Object get(ListaSkillEditImpl obj) {
                return obj.getCargos();
            }

            public void put(ListaSkillEditImpl obj, Object value) {
                obj.setCargos((CargosImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(ListaSkillEditImpl object);

        public abstract void put(ListaSkillEditImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int SKLLID = AttributesEnum.SkllId.index();
    public static final int CRGOID = AttributesEnum.CrgoId.index();
    public static final int SKLLNOMBRE = AttributesEnum.SkllNombre.index();
    public static final int CARGOS = AttributesEnum.Cargos.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ListaSkillEditImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("Andes2.model.vo.ListaSkillEdit");
    }

    /**
     * Gets the attribute value for SkllId, using the alias name SkllId.
     * @return the value of SkllId
     */
    public String getSkllId() {
        return (String)getAttributeInternal(SKLLID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SkllId.
     * @param value value to set the SkllId
     */
    public void setSkllId(String value) {
        setAttributeInternal(SKLLID, value);
    }

    /**
     * Gets the attribute value for CrgoId, using the alias name CrgoId.
     * @return the value of CrgoId
     */
    public String getCrgoId() {
        return (String)getAttributeInternal(CRGOID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CrgoId.
     * @param value value to set the CrgoId
     */
    public void setCrgoId(String value) {
        setAttributeInternal(CRGOID, value);
    }

    /**
     * Gets the attribute value for SkllNombre, using the alias name SkllNombre.
     * @return the value of SkllNombre
     */
    public String getSkllNombre() {
        return (String)getAttributeInternal(SKLLNOMBRE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SkllNombre.
     * @param value value to set the SkllNombre
     */
    public void setSkllNombre(String value) {
        setAttributeInternal(SKLLNOMBRE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity CargosImpl.
     */
    public CargosImpl getCargos() {
        return (CargosImpl)getAttributeInternal(CARGOS);
    }

    /**
     * Sets <code>value</code> as the associated entity CargosImpl.
     */
    public void setCargos(CargosImpl value) {
        setAttributeInternal(CARGOS, value);
    }

    /**
     * @param skllId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String skllId) {
        return new Key(new Object[]{skllId});
    }


}
