package Andes2.model.vo;

import java.math.BigDecimal;

import oracle.jbo.Key;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 01 19:49:25 CLT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RegimenDeTrabajoImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        RgtrSeqCdg {
            public Object get(RegimenDeTrabajoImpl obj) {
                return obj.getRgtrSeqCdg();
            }

            public void put(RegimenDeTrabajoImpl obj, Object value) {
                obj.setRgtrSeqCdg((BigDecimal)value);
            }
        }
        ,
        RgtrNombre {
            public Object get(RegimenDeTrabajoImpl obj) {
                return obj.getRgtrNombre();
            }

            public void put(RegimenDeTrabajoImpl obj, Object value) {
                obj.setRgtrNombre((String)value);
            }
        }
        ,
        RgtrDiasTrabajados {
            public Object get(RegimenDeTrabajoImpl obj) {
                return obj.getRgtrDiasTrabajados();
            }

            public void put(RegimenDeTrabajoImpl obj, Object value) {
                obj.setRgtrDiasTrabajados((BigDecimal)value);
            }
        }
        ,
        RgtrDiasDescansados {
            public Object get(RegimenDeTrabajoImpl obj) {
                return obj.getRgtrDiasDescansados();
            }

            public void put(RegimenDeTrabajoImpl obj, Object value) {
                obj.setRgtrDiasDescansados((BigDecimal)value);
            }
        }
        ,
        RgtrMaxNoches {
            public Object get(RegimenDeTrabajoImpl obj) {
                return obj.getRgtrMaxNoches();
            }

            public void put(RegimenDeTrabajoImpl obj, Object value) {
                obj.setRgtrMaxNoches((BigDecimal)value);
            }
        }
        ,
        RgtrLibresPostSalientes {
            public Object get(RegimenDeTrabajoImpl obj) {
                return obj.getRgtrLibresPostSalientes();
            }

            public void put(RegimenDeTrabajoImpl obj, Object value) {
                obj.setRgtrLibresPostSalientes((BigDecimal)value);
            }
        }
        ,
        RgtrFinesSemanaLibres {
            public Object get(RegimenDeTrabajoImpl obj) {
                return obj.getRgtrFinesSemanaLibres();
            }

            public void put(RegimenDeTrabajoImpl obj, Object value) {
                obj.setRgtrFinesSemanaLibres((BigDecimal)value);
            }
        }
        ,
        RgtrDomingosLibres {
            public Object get(RegimenDeTrabajoImpl obj) {
                return obj.getRgtrDomingosLibres();
            }

            public void put(RegimenDeTrabajoImpl obj, Object value) {
                obj.setRgtrDomingosLibres((BigDecimal)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(RegimenDeTrabajoImpl object);

        public abstract void put(RegimenDeTrabajoImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int RGTRSEQCDG = AttributesEnum.RgtrSeqCdg.index();
    public static final int RGTRNOMBRE = AttributesEnum.RgtrNombre.index();
    public static final int RGTRDIASTRABAJADOS = AttributesEnum.RgtrDiasTrabajados.index();
    public static final int RGTRDIASDESCANSADOS = AttributesEnum.RgtrDiasDescansados.index();
    public static final int RGTRMAXNOCHES = AttributesEnum.RgtrMaxNoches.index();
    public static final int RGTRLIBRESPOSTSALIENTES = AttributesEnum.RgtrLibresPostSalientes.index();
    public static final int RGTRFINESSEMANALIBRES = AttributesEnum.RgtrFinesSemanaLibres.index();
    public static final int RGTRDOMINGOSLIBRES = AttributesEnum.RgtrDomingosLibres.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RegimenDeTrabajoImpl() {
    }

    /**
     * Gets the attribute value for RgtrSeqCdg, using the alias name RgtrSeqCdg.
     * @return the value of RgtrSeqCdg
     */
    public BigDecimal getRgtrSeqCdg() {
        return (BigDecimal)getAttributeInternal(RGTRSEQCDG);
    }

    /**
     * Sets <code>value</code> as the attribute value for RgtrSeqCdg.
     * @param value value to set the RgtrSeqCdg
     */
    public void setRgtrSeqCdg(BigDecimal value) {
        setAttributeInternal(RGTRSEQCDG, value);
    }

    /**
     * Gets the attribute value for RgtrNombre, using the alias name RgtrNombre.
     * @return the value of RgtrNombre
     */
    public String getRgtrNombre() {
        return (String)getAttributeInternal(RGTRNOMBRE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RgtrNombre.
     * @param value value to set the RgtrNombre
     */
    public void setRgtrNombre(String value) {
        setAttributeInternal(RGTRNOMBRE, value);
    }

    /**
     * Gets the attribute value for RgtrDiasTrabajados, using the alias name RgtrDiasTrabajados.
     * @return the value of RgtrDiasTrabajados
     */
    public BigDecimal getRgtrDiasTrabajados() {
        return (BigDecimal)getAttributeInternal(RGTRDIASTRABAJADOS);
    }

    /**
     * Sets <code>value</code> as the attribute value for RgtrDiasTrabajados.
     * @param value value to set the RgtrDiasTrabajados
     */
    public void setRgtrDiasTrabajados(BigDecimal value) {
        setAttributeInternal(RGTRDIASTRABAJADOS, value);
    }

    /**
     * Gets the attribute value for RgtrDiasDescansados, using the alias name RgtrDiasDescansados.
     * @return the value of RgtrDiasDescansados
     */
    public BigDecimal getRgtrDiasDescansados() {
        return (BigDecimal)getAttributeInternal(RGTRDIASDESCANSADOS);
    }

    /**
     * Sets <code>value</code> as the attribute value for RgtrDiasDescansados.
     * @param value value to set the RgtrDiasDescansados
     */
    public void setRgtrDiasDescansados(BigDecimal value) {
        setAttributeInternal(RGTRDIASDESCANSADOS, value);
    }

    /**
     * Gets the attribute value for RgtrMaxNoches, using the alias name RgtrMaxNoches.
     * @return the value of RgtrMaxNoches
     */
    public BigDecimal getRgtrMaxNoches() {
        return (BigDecimal)getAttributeInternal(RGTRMAXNOCHES);
    }

    /**
     * Sets <code>value</code> as the attribute value for RgtrMaxNoches.
     * @param value value to set the RgtrMaxNoches
     */
    public void setRgtrMaxNoches(BigDecimal value) {
        setAttributeInternal(RGTRMAXNOCHES, value);
    }

    /**
     * Gets the attribute value for RgtrLibresPostSalientes, using the alias name RgtrLibresPostSalientes.
     * @return the value of RgtrLibresPostSalientes
     */
    public BigDecimal getRgtrLibresPostSalientes() {
        return (BigDecimal)getAttributeInternal(RGTRLIBRESPOSTSALIENTES);
    }

    /**
     * Sets <code>value</code> as the attribute value for RgtrLibresPostSalientes.
     * @param value value to set the RgtrLibresPostSalientes
     */
    public void setRgtrLibresPostSalientes(BigDecimal value) {
        setAttributeInternal(RGTRLIBRESPOSTSALIENTES, value);
    }

    /**
     * Gets the attribute value for RgtrFinesSemanaLibres, using the alias name RgtrFinesSemanaLibres.
     * @return the value of RgtrFinesSemanaLibres
     */
    public BigDecimal getRgtrFinesSemanaLibres() {
        return (BigDecimal)getAttributeInternal(RGTRFINESSEMANALIBRES);
    }

    /**
     * Sets <code>value</code> as the attribute value for RgtrFinesSemanaLibres.
     * @param value value to set the RgtrFinesSemanaLibres
     */
    public void setRgtrFinesSemanaLibres(BigDecimal value) {
        setAttributeInternal(RGTRFINESSEMANALIBRES, value);
    }

    /**
     * Gets the attribute value for RgtrDomingosLibres, using the alias name RgtrDomingosLibres.
     * @return the value of RgtrDomingosLibres
     */
    public BigDecimal getRgtrDomingosLibres() {
        return (BigDecimal)getAttributeInternal(RGTRDOMINGOSLIBRES);
    }

    /**
     * Sets <code>value</code> as the attribute value for RgtrDomingosLibres.
     * @param value value to set the RgtrDomingosLibres
     */
    public void setRgtrDomingosLibres(BigDecimal value) {
        setAttributeInternal(RGTRDOMINGOSLIBRES, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @param rgtrSeqCdg key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal rgtrSeqCdg) {
        return new Key(new Object[]{rgtrSeqCdg});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("Andes2.model.vo.RegimenDeTrabajo");
    }
}
