package Andes2.model.vo;

import java.math.BigDecimal;

import oracle.jbo.domain.RowID;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 01 20:14:28 CLT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TurnosFijadosImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        EmplRut {
            public Object get(TurnosFijadosImpl obj) {
                return obj.getEmplRut();
            }

            public void put(TurnosFijadosImpl obj, Object value) {
                obj.setEmplRut((String)value);
            }
        }
        ,
        TurnNombre {
            public Object get(TurnosFijadosImpl obj) {
                return obj.getTurnNombre();
            }

            public void put(TurnosFijadosImpl obj, Object value) {
                obj.setTurnNombre((String)value);
            }
        }
        ,
        FjagDia {
            public Object get(TurnosFijadosImpl obj) {
                return obj.getFjagDia();
            }

            public void put(TurnosFijadosImpl obj, Object value) {
                obj.setFjagDia((Timestamp)value);
            }
        }
        ,
        FjarVersion {
            public Object get(TurnosFijadosImpl obj) {
                return obj.getFjarVersion();
            }

            public void put(TurnosFijadosImpl obj, Object value) {
                obj.setFjarVersion((BigDecimal)value);
            }
        }
        ,
        RowID {
            public Object get(TurnosFijadosImpl obj) {
                return obj.getRowID();
            }

            public void put(TurnosFijadosImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EmpleadosEdit {
            public Object get(TurnosFijadosImpl obj) {
                return obj.getEmpleadosEdit();
            }

            public void put(TurnosFijadosImpl obj, Object value) {
                obj.setEmpleadosEdit((EntityImpl)value);
            }
        }
        ,
        TurnosEdit {
            public Object get(TurnosFijadosImpl obj) {
                return obj.getTurnosEdit();
            }

            public void put(TurnosFijadosImpl obj, Object value) {
                obj.setTurnosEdit((TurnosEditImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(TurnosFijadosImpl object);

        public abstract void put(TurnosFijadosImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int EMPLRUT = AttributesEnum.EmplRut.index();
    public static final int TURNNOMBRE = AttributesEnum.TurnNombre.index();
    public static final int FJAGDIA = AttributesEnum.FjagDia.index();
    public static final int FJARVERSION = AttributesEnum.FjarVersion.index();
    public static final int ROWID = AttributesEnum.RowID.index();
    public static final int EMPLEADOSEDIT = AttributesEnum.EmpleadosEdit.index();
    public static final int TURNOSEDIT = AttributesEnum.TurnosEdit.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TurnosFijadosImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("Andes2.model.vo.TurnosFijados");
    }

    /**
     * Gets the attribute value for EmplRut, using the alias name EmplRut.
     * @return the value of EmplRut
     */
    public String getEmplRut() {
        return (String)getAttributeInternal(EMPLRUT);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmplRut.
     * @param value value to set the EmplRut
     */
    public void setEmplRut(String value) {
        setAttributeInternal(EMPLRUT, value);
    }

    /**
     * Gets the attribute value for TurnNombre, using the alias name TurnNombre.
     * @return the value of TurnNombre
     */
    public String getTurnNombre() {
        return (String)getAttributeInternal(TURNNOMBRE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TurnNombre.
     * @param value value to set the TurnNombre
     */
    public void setTurnNombre(String value) {
        setAttributeInternal(TURNNOMBRE, value);
    }

    /**
     * Gets the attribute value for FjagDia, using the alias name FjagDia.
     * @return the value of FjagDia
     */
    public Timestamp getFjagDia() {
        return (Timestamp)getAttributeInternal(FJAGDIA);
    }

    /**
     * Sets <code>value</code> as the attribute value for FjagDia.
     * @param value value to set the FjagDia
     */
    public void setFjagDia(Timestamp value) {
        setAttributeInternal(FJAGDIA, value);
    }

    /**
     * Gets the attribute value for FjarVersion, using the alias name FjarVersion.
     * @return the value of FjarVersion
     */
    public BigDecimal getFjarVersion() {
        return (BigDecimal)getAttributeInternal(FJARVERSION);
    }

    /**
     * Sets <code>value</code> as the attribute value for FjarVersion.
     * @param value value to set the FjarVersion
     */
    public void setFjarVersion(BigDecimal value) {
        setAttributeInternal(FJARVERSION, value);
    }

    /**
     * Gets the attribute value for RowID, using the alias name RowID.
     * @return the value of RowID
     */
    public RowID getRowID() {
        return (RowID)getAttributeInternal(ROWID);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getEmpleadosEdit() {
        return (EntityImpl)getAttributeInternal(EMPLEADOSEDIT);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setEmpleadosEdit(EntityImpl value) {
        setAttributeInternal(EMPLEADOSEDIT, value);
    }

    /**
     * @return the associated entity TurnosEditImpl.
     */
    public TurnosEditImpl getTurnosEdit() {
        return (TurnosEditImpl)getAttributeInternal(TURNOSEDIT);
    }

    /**
     * Sets <code>value</code> as the associated entity TurnosEditImpl.
     */
    public void setTurnosEdit(TurnosEditImpl value) {
        setAttributeInternal(TURNOSEDIT, value);
    }

}
