package Andes2.model.vo;

import java.math.BigDecimal;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 01 19:52:10 CLT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TurnosEditImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        TurnSeqCdg {
            public Object get(TurnosEditImpl obj) {
                return obj.getTurnSeqCdg();
            }

            public void put(TurnosEditImpl obj, Object value) {
                obj.setTurnSeqCdg((BigDecimal)value);
            }
        }
        ,
        TurnNombre {
            public Object get(TurnosEditImpl obj) {
                return obj.getTurnNombre();
            }

            public void put(TurnosEditImpl obj, Object value) {
                obj.setTurnNombre((String)value);
            }
        }
        ,
        TurnTipo {
            public Object get(TurnosEditImpl obj) {
                return obj.getTurnTipo();
            }

            public void put(TurnosEditImpl obj, Object value) {
                obj.setTurnTipo((String)value);
            }
        }
        ,
        TurnHoraIngreso {
            public Object get(TurnosEditImpl obj) {
                return obj.getTurnHoraIngreso();
            }

            public void put(TurnosEditImpl obj, Object value) {
                obj.setTurnHoraIngreso((String)value);
            }
        }
        ,
        TurnHoraSalida {
            public Object get(TurnosEditImpl obj) {
                return obj.getTurnHoraSalida();
            }

            public void put(TurnosEditImpl obj, Object value) {
                obj.setTurnHoraSalida((String)value);
            }
        }
        ,
        TurnosFijados {
            public Object get(TurnosEditImpl obj) {
                return obj.getTurnosFijados();
            }

            public void put(TurnosEditImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TurnosRestricciones {
            public Object get(TurnosEditImpl obj) {
                return obj.getTurnosRestricciones();
            }

            public void put(TurnosEditImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(TurnosEditImpl object);

        public abstract void put(TurnosEditImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int TURNSEQCDG = AttributesEnum.TurnSeqCdg.index();
    public static final int TURNNOMBRE = AttributesEnum.TurnNombre.index();
    public static final int TURNTIPO = AttributesEnum.TurnTipo.index();
    public static final int TURNHORAINGRESO = AttributesEnum.TurnHoraIngreso.index();
    public static final int TURNHORASALIDA = AttributesEnum.TurnHoraSalida.index();
    public static final int TURNOSFIJADOS = AttributesEnum.TurnosFijados.index();
    public static final int TURNOSRESTRICCIONES = AttributesEnum.TurnosRestricciones.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TurnosEditImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("Andes2.model.vo.TurnosEdit");
    }

    /**
     * Gets the attribute value for TurnSeqCdg, using the alias name TurnSeqCdg.
     * @return the value of TurnSeqCdg
     */
    public BigDecimal getTurnSeqCdg() {
        return (BigDecimal)getAttributeInternal(TURNSEQCDG);
    }

    /**
     * Sets <code>value</code> as the attribute value for TurnSeqCdg.
     * @param value value to set the TurnSeqCdg
     */
    public void setTurnSeqCdg(BigDecimal value) {
        setAttributeInternal(TURNSEQCDG, value);
    }

    /**
     * Gets the attribute value for TurnNombre, using the alias name TurnNombre.
     * @return the value of TurnNombre
     */
    public String getTurnNombre() {
        return (String)getAttributeInternal(TURNNOMBRE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TurnNombre.
     * @param value value to set the TurnNombre
     */
    public void setTurnNombre(String value) {
        setAttributeInternal(TURNNOMBRE, value);
    }

    /**
     * Gets the attribute value for TurnTipo, using the alias name TurnTipo.
     * @return the value of TurnTipo
     */
    public String getTurnTipo() {
        return (String)getAttributeInternal(TURNTIPO);
    }

    /**
     * Sets <code>value</code> as the attribute value for TurnTipo.
     * @param value value to set the TurnTipo
     */
    public void setTurnTipo(String value) {
        setAttributeInternal(TURNTIPO, value);
    }

    /**
     * Gets the attribute value for TurnHoraIngreso, using the alias name TurnHoraIngreso.
     * @return the value of TurnHoraIngreso
     */
    public String getTurnHoraIngreso() {
        return (String)getAttributeInternal(TURNHORAINGRESO);
    }

    /**
     * Sets <code>value</code> as the attribute value for TurnHoraIngreso.
     * @param value value to set the TurnHoraIngreso
     */
    public void setTurnHoraIngreso(String value) {
        setAttributeInternal(TURNHORAINGRESO, value);
    }

    /**
     * Gets the attribute value for TurnHoraSalida, using the alias name TurnHoraSalida.
     * @return the value of TurnHoraSalida
     */
    public String getTurnHoraSalida() {
        return (String)getAttributeInternal(TURNHORASALIDA);
    }

    /**
     * Sets <code>value</code> as the attribute value for TurnHoraSalida.
     * @param value value to set the TurnHoraSalida
     */
    public void setTurnHoraSalida(String value) {
        setAttributeInternal(TURNHORASALIDA, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTurnosFijados() {
        return (RowIterator)getAttributeInternal(TURNOSFIJADOS);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTurnosRestricciones() {
        return (RowIterator)getAttributeInternal(TURNOSRESTRICCIONES);
    }

    /**
     * @param turnNombre key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String turnNombre) {
        return new Key(new Object[]{turnNombre});
    }


}
