package Andes2.model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 12 14:53:45 CLT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ViewObj1Impl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ViewObj1Impl() {
    }
}
